export const ADD_BILL = "ADD_BILL"
export const DELETE_BILL = "DELETE_BILL"
export const UPDATE_BILL = "UPDATE_BILL"
export const GET_BILL = "GET_BILL"
export const LATEST_ID = "LATEST_ID"
export const GET_BILL_RECORD = "GET_BILL_RECORD"